import { COUNTRIES_DICTIONARY, COUNTRY_PARAM } from './const.js'

export function parseCountry(country) {
  switch (country) {
    case COUNTRY_PARAM.ARGENTINA:
      return COUNTRIES_DICTIONARY.ARGENTINA
    case COUNTRY_PARAM.BOLIVIA:
      return COUNTRIES_DICTIONARY.BOLIVIA
    case COUNTRY_PARAM.BRASIL:
      return COUNTRIES_DICTIONARY.BRASIL
    case COUNTRY_PARAM.CHILE:
      return COUNTRIES_DICTIONARY.CHILE
    case COUNTRY_PARAM.COLOMBIA:
      return COUNTRIES_DICTIONARY.COLOMBIA
    case COUNTRY_PARAM.COSTA_RICA:
      return COUNTRIES_DICTIONARY.COSTA_RICA
    case COUNTRY_PARAM.CUBA:
      return COUNTRIES_DICTIONARY.CUBA
    case COUNTRY_PARAM.ECUADOR:
      return COUNTRIES_DICTIONARY.ECUADOR
    case COUNTRY_PARAM.EL_SALVADOR:
      return COUNTRIES_DICTIONARY.EL_SALVADOR
    case COUNTRY_PARAM.ESPANA:
      return COUNTRIES_DICTIONARY.ESPANA
    case COUNTRY_PARAM.GUATEMALA:
      return COUNTRIES_DICTIONARY.GUATEMALA
    case COUNTRY_PARAM.HAITI:
      return COUNTRIES_DICTIONARY.HAITI
    case COUNTRY_PARAM.HONDURAS:
      return COUNTRIES_DICTIONARY.HONDURAS
    case COUNTRY_PARAM.MEXICO:
      return COUNTRIES_DICTIONARY.MEXICO
    case COUNTRY_PARAM.NICARAGUA:
      return COUNTRIES_DICTIONARY.NICARAGUA
    case COUNTRY_PARAM.PANAMA:
      return COUNTRIES_DICTIONARY.PANAMA
    case COUNTRY_PARAM.PARAGUAY:
      return COUNTRIES_DICTIONARY.PARAGUAY
    case COUNTRY_PARAM.PERU:
      return COUNTRIES_DICTIONARY.PERU
    case COUNTRY_PARAM.REPUBLICA_DOMINICANA:
      return COUNTRIES_DICTIONARY.REPUBLICA_DOMINICANA
    case COUNTRY_PARAM.URUGUAY:
      return COUNTRIES_DICTIONARY.URUGUAY
    case COUNTRY_PARAM.VENEZUELA:
      return COUNTRIES_DICTIONARY.VENEZUELA
    default:
      return COUNTRIES_DICTIONARY.ESPANA
  }
}

